### ISSUE TITLE
Run unit tests on TravisCI

### ISSUE THREAD

**Issue by bahmutov** [repo-utils/parse-github-repo-url#2]
@jonathanong could you enable the build for this repo on TravisCI please? https://travis-ci.org/profile/repo-utils - it would be very nice to auto test, and if there is a github and npm token we could even semantically release?

**Comment by jonathanong** [comment]
added you as an admin for this repo. you should be able to do it yoruself

**Comment by bahmutov** [comment]
Weird, still unable to flip
![screen shot 2016-04-13 at 15 49 16](https://cloud.githubusercontent.com/assets/2212006/14507143/57461886-018f-11e6-97b6-49c5592c7a2f.png)
 the switch

**Comment by jonathanong** [comment]
ugh. k enabling it

**Comment by bahmutov** [comment]
done
