### ISSUE TITLE
Support `subgroup` in gitlab repo URL

### ISSUE THREAD

**Issue by canercandan** [repo-utils/parse-github-repo-url#7]
gitlab.com introduced in 9.0 the `Subgroups` (https://docs.gitlab.com/ce/user/group/subgroups/), from there on an user can create a repository within a subgroup, the URL will therefore looks like:

```
https://gitlab.com/GROUP/SUBGROUP/PROJECT
```

but it can also be nested with several (infinitely) chained subgroups:

```
https://gitlab.com/GROUP/SUBGROUP1/SUBGROUP2/SUBGROUP3/PROJECT
```

Issue identified first there: https://gitlab.com/hyper-expanse/semantic-release-gitlab-releaser/issues/5

FYI just reproduced the relevant error below:

```sh
> var parser = require('parse-github-repo-url')
undefined
> parser('git@gitlab.com:GROUP/SUBGROUP/PROJECT.git')
false
> parser('git@gitlab.com:GROUP/PROJECT.git')
[ 'GROUP', 'PROJECT', '' ]
> 
```

**Comment by canercandan** [comment]
The following regex works properly with the nested subgroup-based gitlab URLs:

**Example with a single subgroup:**
```sh
> /^\/([\w-.]+)\/((?:[\w-.]+\/)+)([\w-.]+)$/.exec('/GROUP/SUBGROUP/PROJECT')
[ '/GROUP/SUBGROUP/PROJECT',
  'GROUP',
  'SUBGROUP/',
  'PROJECT',
  index: 0,
  input: '/GROUP/SUBGROUP/PROJECT' ]
```

**Example with 2 nested subgroups:**
```sh
> /^\/([\w-.]+)\/((?:[\w-.]+\/)+)([\w-.]+)$/.exec('/GROUP/SUBGROUP/SUBGROUP2/PROJECT')
[ '/GROUP/SUBGROUP/SUBGROUP2/PROJECT',
  'GROUP',
  'SUBGROUP/SUBGROUP2/',
  'PROJECT',
  index: 0,
  input: '/GROUP/SUBGROUP/SUBGROUP2/PROJECT' ]
```

**Example with 3 nested subgroups:**
```sh
> /^\/([\w-.]+)\/((?:[\w-.]+\/)+)([\w-.]+)$/.exec('/GROUP/SUBGROUP/SUBGROUP2/SUBGROUP3/PROJECT')
[ '/GROUP/SUBGROUP/SUBGROUP2/SUBGROUP3/PROJECT',
  'GROUP',
  'SUBGROUP/SUBGROUP2/SUBGROUP3/',
  'PROJECT',
  index: 0,
  input: '/GROUP/SUBGROUP/SUBGROUP2/SUBGROUP3/PROJECT' ]
```

**Comment by bahmutov** [comment]
Love it! If you want to submit pull requests with the above test cases, would love to merge and release

**Comment by canercandan** [comment]
@bahmutov sure you can check this out https://github.com/repo-utils/parse-github-repo-url/pull/8 thanks

**Comment by canercandan** [comment]
I run the test stack upstream with those changes on https://github.com/stevemao/get-pkg-repo but I am getting an error:

```sh
$ npm run test

> get-pkg-repo@1.3.0 test /tmp/get-pkg-repo
> npm run-script lint && mocha


> get-pkg-repo@1.3.0 lint /tmp/get-pkg-repo
> jshint *.js --exclude node_modules && jscs *.js



  ✓ should parse github http
  ✓ should parse github https
  ✓ should parse github ssh
  ✓ should parse private gitlab ssh
  ✓ should parse github short
  ✓ should parse bitbucket
  ✓ should parse svn
  ✓ should parse https
  ✓ should parse a url with an @
  ✓ should fix bad protocal
  ✓ should work with a json
  ✓ should work if there is a typo
  ✓ should error if cannot get repository
  ✓ should parse github enterprise http url
  ✓ should parse simple unknown host
  1) should parse complex unknown host
  ✓ should parse weird unknown host

  16 passing (31ms)
  1 failing

  1)  should parse complex unknown host:
     AssertionError: 'scm/conventional-changelog' === undefined
      at assertRepo (test.js:14:10)
      at Context.<anonymous> (test.js:172:3)
…
```

I will try to reproduce the same error in my PR.

**Comment by canercandan** [comment]
@bahmutov I fixed the last issue and squashed the new changes into the same PR https://github.com/repo-utils/parse-github-repo-url/pull/8 feel free to review and merge. Thanks.

**Comment by canercandan** [comment]
therefore the package `get-pkg-repo` tests works now with this new PR:

```sh
$ npm run test

> get-pkg-repo@1.3.0 test /tmp/get-pkg-repo
> npm run-script lint && mocha


> get-pkg-repo@1.3.0 lint /tmp/get-pkg-repo
> jshint *.js --exclude node_modules && jscs *.js



  ✓ should parse github http
  ✓ should parse github https
  ✓ should parse github ssh
  ✓ should parse private gitlab ssh
  ✓ should parse github short
  ✓ should parse bitbucket
  ✓ should parse svn
  ✓ should parse https
  ✓ should parse a url with an @
  ✓ should fix bad protocal
  ✓ should work with a json
  ✓ should work if there is a typo
  ✓ should error if cannot get repository
  ✓ should parse github enterprise http url
  ✓ should parse simple unknown host
  ✓ should parse complex unknown host
  ✓ should parse weird unknown host

  17 passing (32ms)
```

**Comment by canercandan** [comment]
gitlab API also requires the project id to be escaped therefore a URL such as:

```
https://gitlab.team.com/user/subgroup1/subgroup2/subgroup3/test1.git
```

should return the fields:

```
user = user%2Fsubgroup1%2Fsubgroup2%2Fsubgroup3
project = test1
```

I updated the PR to reflect this issue and cover it with a new test case.

**Comment by canercandan** [comment]
after having investigated a bit more on the escaping thing, I think it's better to not do this here and leave it to the upstream libs to escape the path if necessary depending on their use case, for instance the package https://www.npmjs.com/package/gitlab escapes the project ID that contains the user/group/subgroups and the project name. So I am removing the `slash` replacement line of code there.

**Comment by hutson** [comment]
A GitLab issue was recently filed against `semantic-release-gitlab` (https://gitlab.com/hyper-expanse/semantic-release-gitlab/issues/25), and based on the efforts of the person who filed the issue, I believe the culprit is the use of GitLab sub-groups.

I believe @canercandan's work in #8 would address the bug report.
